apiVersion: 1

datasources:
  - name: Prometheus Default
    description: Prometheus Default(localhost:9090)
    #    use this uid for every datasource specified in a dashboard config json file(the 'performance-measurement.json')
    uid: ds-default-prometheus
    type: prometheus
    url: http://127.0.0.1:9090
    isDefault: true
    access: proxy
    editable: true